### ISSUE TITLE
Error running Demo

### ISSUE THREAD

**Issue by judavi** [in-toto/demo#12]
Hello!!
I'm trying to follow the demo. I'm running the demo on a clean CentOS machine. I installed virtualenvwrapper and followed each step. 
But when I reach the step to create the layout I'm getting:

```
[judavi@grafeas owner_alice]$ python create_layout.py 
Traceback (most recent call last):
  File "create_layout.py", line 1, in <module>
    from in_toto.util import import_rsa_key_from_file
  File "/usr/lib/python2.7/site-packages/in_toto/util.py", line 12, in <module>
    import securesystemslib.gpg.functions
  File "/usr/lib/python2.7/site-packages/securesystemslib/gpg/functions.py", line 21, in <module>
    import securesystemslib.gpg.common
  File "/usr/lib/python2.7/site-packages/securesystemslib/gpg/common.py", line 25, in <module>
    import securesystemslib.gpg.util
  File "/usr/lib/python2.7/site-packages/securesystemslib/gpg/util.py", line 28, in <module>
    import securesystemslib.process
  File "/usr/lib/python2.7/site-packages/securesystemslib/process.py", line 42, in <module>
    DEVNULL = subprocess.DEVNULL
AttributeError: 'module' object has no attribute 'DEVNULL'
```
Please, could you advise what I'm missing? Thanks!

```
[judavi@grafeas owner_alice]$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
[judavi@grafeas owner_alice]$ python --version
Python 2.7.5
[judavi@grafeas owner_alice]$ gpg --version
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ?, ?, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

```

**Comment by lukpueh** [comment]
Thanks for your request, @judavi. Can you try updating `subprocess32`? I suspect that you have a version below 3.5.0rc1, which is where [`subprocess.DEVNULL` support was added](https://github.com/google/python-subprocess32/blob/f5d96717bb266ed2c10fbd8d8dc65b30aab534e9/ChangeLog#L62).

**Comment by judavi** [comment]
@lukpueh thank you! you suggestion fixed the issue!
